-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 20:46:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Adreces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adreces` (
  `id_Adreca` INT NOT NULL,
  `carrer_Adreca` VARCHAR(45) NULL,
  `numero_Adreca` INT NULL,
  `pis_Adreca` INT NULL,
  `porta_Adreca` INT NULL,
  `ciutat_Adreca` VARCHAR(45) NULL,
  `codipostal_Adreca` INT NULL,
  `pais_Adreca` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Adreca`),
  UNIQUE INDEX `id_Adreca_UNIQUE` (`id_Adreca` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveïdors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveïdors` (
  `id_Proveidor` INT NOT NULL,
  `nom_Proveidor` VARCHAR(45) NULL,
  `telefon_Proveidor` INT NULL,
  `fax_Proveidor` INT NULL,
  `nif_Proveidor` VARCHAR(45) NULL,
  `Adreces_id_Adreca` INT NOT NULL,
  PRIMARY KEY (`id_Proveidor`),
  UNIQUE INDEX `id_Proveidor_UNIQUE` (`id_Proveidor` ASC),
  INDEX `fk_Proveïdors_Adreces_idx` (`Adreces_id_Adreca` ASC),
  CONSTRAINT `fk_Proveïdors_Adreces`
    FOREIGN KEY (`Adreces_id_Adreca`)
    REFERENCES `mydb`.`Adreces` (`id_Adreca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ulleres` (
  `id_Ullera` INT NOT NULL,
  `marca_Ullera` VARCHAR(45) NULL,
  `graduacio_Ullera` INT NULL,
  `tipusmuntura_Ullera` VARCHAR(45) NULL,
  `colormuntura_Ullera` VARCHAR(45) NULL,
  `colorvidre_Ullera` VARCHAR(45) NULL,
  `preu_Ullera` INT NULL,
  PRIMARY KEY (`id_Ullera`),
  UNIQUE INDEX `id_Ullera_UNIQUE` (`id_Ullera` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id_Client` INT NOT NULL,
  `nom_Client` VARCHAR(45) NULL,
  `telefon_Client` VARCHAR(45) NULL,
  `email_Client` VARCHAR(45) NULL,
  `dataregistre_Client` DATETIME NULL,
  `recomenatper_Client` VARCHAR(45) NULL,
  `Adreces_id_Adreca` INT NOT NULL,
  PRIMARY KEY (`id_Client`),
  INDEX `fk_Clients_Adreces1_idx` (`Adreces_id_Adreca` ASC),
  CONSTRAINT `fk_Clients_Adreces1`
    FOREIGN KEY (`Adreces_id_Adreca`)
    REFERENCES `mydb`.`Adreces` (`id_Adreca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleats` (
  `id_Empleat` INT NOT NULL,
  `nom_Empleat` VARCHAR(45) NULL,
  `cognom_Empleat` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Empleat`),
  UNIQUE INDEX `id_Empleat_UNIQUE` (`id_Empleat` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendes` (
  `id_Venda` INT NOT NULL,
  `Empleats_id_Empleat` INT NOT NULL,
  `Ulleres_id_Ullera` INT NOT NULL,
  `Proveïdors_id_Proveidor` INT NOT NULL,
  `Clients_id_Client` INT NOT NULL,
  PRIMARY KEY (`id_Venda`),
  UNIQUE INDEX `id_Venda_UNIQUE` (`id_Venda` ASC),
  INDEX `fk_Vendes_Empleats1_idx` (`Empleats_id_Empleat` ASC),
  INDEX `fk_Vendes_Ulleres1_idx` (`Ulleres_id_Ullera` ASC),
  INDEX `fk_Vendes_Proveïdors1_idx` (`Proveïdors_id_Proveidor` ASC),
  INDEX `fk_Vendes_Clients1_idx` (`Clients_id_Client` ASC),
  CONSTRAINT `fk_Vendes_Empleats1`
    FOREIGN KEY (`Empleats_id_Empleat`)
    REFERENCES `mydb`.`Empleats` (`id_Empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendes_Ulleres1`
    FOREIGN KEY (`Ulleres_id_Ullera`)
    REFERENCES `mydb`.`Ulleres` (`id_Ullera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendes_Proveïdors1`
    FOREIGN KEY (`Proveïdors_id_Proveidor`)
    REFERENCES `mydb`.`Proveïdors` (`id_Proveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendes_Clients1`
    FOREIGN KEY (`Clients_id_Client`)
    REFERENCES `mydb`.`Clients` (`id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
